services:
  schneaggchat_db:
    image: mongo:latest
    restart: unless-stopped
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - spring-mongo-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  schneaggchat_db_gui:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@schneaggchat_db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - schneaggchat_db
    networks:
      - spring-mongo-network

  schneaggchat_redis:
    image: redis:7-alpine
    container_name: schneaggchat_redis
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - spring-mongo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  schneaggchatv3server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      schneaggchat_db:
        condition: service_healthy
      schneaggchat_redis:
        condition: service_healthy
    ports:
      - "8083:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@schneaggchat_db:27017/db?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      DEFAULTACCOUNT_PASSWORD: ${DEFAULTACCOUNT_PASSWORD}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

      APNS_TEAM_ID: ${APNS_TEAM_ID}
      APNS_KEY_ID: ${APNS_KEY_ID}
      APNS_BUNDLE_ID: ${APNS_BUNDLE_ID}
      APNS_DEBUG: ${APNS_DEBUG}

      SPRING_DATA_REDIS_HOST: schneaggchat_redis
      SPRING_DATA_REDIS_PORT: "6379"

    networks:
      - spring-mongo-network
    volumes:
      - app-images-messages:/app/images_messages
      - app-images:/app/images
      - app-audio-messages:/app/audio_messages
      - ./schneaggchatv3-firebase-admin.json:/app/schneaggchatv3-firebase-admin.json:ro
      - ./ApnsAuthKey.p8:/app/ApnsAuthKey.p8:ro

networks:
  spring-mongo-network:
    driver: bridge

volumes:
  app-images:
  app-images-messages:
  app-audio-messages:
  redis-data:
