spring.application.name=schneaggchatv3server

#logging
logging.pattern.console=%d{HH:mm:ss} %p %c - %m%n
logging.level.org.springframework.web=ERROR
logging.level.org.springframework.core.env=ERROR
logging.level.org.springframework.boot.context.config=ERROR

#Always print the error message in the response
spring.web.error.include-message=always

#Mongodb config
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.mongodb.database=db
spring.data.mongodb.auto-index-creation=true

#Json web token
jwt.secret=${JWT_SECRET}

#Password for Google play test account
defaultaccount.password=${DEFAULTACCOUNT_PASSWORD}

#Email for email verification etc
spring.mail.test-connection=false
spring.mail.username=${EMAIL}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true